# Generated by Django 6.0.3 on 2026-03-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signword',
            name='needs_ssl_bypass',
            field=models.BooleanField(default=False),
        ),
    ]
