# Generated by Django 6.0.3 on 2026-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASLLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='asl_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='asl_videos/')),
            ],
        ),
    ]
