# Generated by Django 6.0.3 on 2026-03-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_signword_needs_ssl_bypass'),
    ]

    operations = [
        migrations.AddField(
            model_name='signword',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
