# Generated by Django 6.0.3 on 2026-04-07 09:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_aslletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aslletter',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='asl_videos/'),
        ),
    ]
