# Generated by Django 6.0.3 on 2026-04-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetcode'),
        ('accounts', '0006_user_organization_name_user_phone_number'),
    ]

    operations = [
    ]
