"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import dj_database_url
import os
from dotenv import load_dotenv

load_dotenv() # This is a security meseaure for my email address to be the reset account email sender
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# We pull this from .env to keep it off GitHub.
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# os.getenv returns a string, so we compare it to 'True' to get a Boolean (True/False).
DEBUG = os.getenv('DEBUG') == 'True'




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'cloudinary',
    'rest_framework',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',
    'accounts',
    'corsheaders',
    #I added those two installed apps so Django can use them --- For user authentication (login, registration, forgot password), the fastest way to deliver is using a library called Djoser. It provides all the REST API endpoints you need out of the box.
    'rest_framework.authtoken',
    'djoser',
    'deaf_hub',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# ==========================================
# CLOUD DATABASE SETUP (NEON POSTGRESQL)
# ==========================================
# We are using Neon (PostgreSQL) instead of the default local db.sqlite3 file.
# This ensures that all developers on the team are reading and writing to the 
# exact same shared database in the cloud, rather than separate local files.
# The 'dj_database_url' package securely translates the Neon connection string.

DATABASES = {
    'default': dj_database_url.config(
        conn_max_age=0,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication', # Tells Django REST Framework to use tokens to identify logged-in users
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication', # Adds Username/Password support
        'rest_framework.authentication.SessionAuthentication', # Adds Browser support
    )
}


# Real Email Configuration (Gmail SMTP)
# SMTP Email Backend for Djoser (Password Reset, Activation, etc.)
# IMPORTANT: Never hardcode passwords here. Always use the .env file!
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASS')
AUTH_USER_MODEL = 'accounts.User'
# Djoser settings for password reset
DJOSER = {
    'SEND_CONFIRMATION_EMAIL': False,
    'LOGIN_FIELD': 'email',  # Makes email the primary login field
    'USER_CREATE_PASSWORD_RETYPE': True, # Forces users to type password twice
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': False,
    'SERIALIZERS': {
        'user_create': 'accounts.serializers.UserRegistrationSerializer',
        'user': 'accounts.serializers.UserRegistrationSerializer',
        'current_user': 'accounts.serializers.UserRegistrationSerializer',
    },
}

# For development, allow all origins (React, Mobile, etc.)

# 1. Allow the ngrok domain to send requests
CSRF_TRUSTED_ORIGINS = [
    'https://tonda-interapophyseal-shelteringly.ngrok-free.dev',
]

# 2. Since this is an API for a mobile app, we also need to relax these
CORS_ALLOW_ALL_ORIGINS = True
ALLOWED_HOSTS = ['*']

# If you want to be specific later:
# CORS_ALLOWED_ORIGINS = ["http://localhost:3000"]

# MEDIA CONFIGURATION
# 1. The URL the browser will use to ask for the file (e.g., your-site.com/media/...)
MEDIA_URL = '/media/'

# 2. The exact folder on your computer where Django should look for those files
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary Credentials
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# Tell Django to route media to Cloudinary
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}